### ISSUE TITLE
Unable to see server numbers

### ISSUE THREAD

**Issue by GalackduQSM** [Astra-Development/Discord-Bot-List-v3#21]
I found a bug on the bot.ejs page, the server number is not displayed and yet there is the code in the page
![image](https://github.com/Astra-Development/Discord-Bot-List-v3/assets/157456816/b81010df-2af6-4df7-9d0c-ab07311ea3d7)
![image](https://github.com/Astra-Development/Discord-Bot-List-v3/assets/157456816/8b61151b-b546-4017-9feb-9b6cb8537726)

**Comment by johnandreopoulos** [comment]
Thank you for your feedback. It appears that the server number is not displayed on the bot.ejs page due to the absence of the botdata.serverCount variable in the codebase.

This feature relies on an older implementation, and I may not fully remember its workings. It was intended to use our API, which might not have been fully developed. As a result, the function seems inactive, reserved for potential updates.
